logging:
  level:
    com:
      github:
        io:
          asyncer:
            r2dbc: DEBUG
server:
  port: '9560'
spring:
  application:
    name: FILE-SERVICE
  r2dbc:
    password: '123456'
    ssl: 'false'
    url: r2dbc:pool:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/blogapp?allowPublicKeyRetrieval=true
    username: cokutan
  profiles:
    active: production
#Publish Application(Register with Eureka)
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  # instance id for eureka server
  instance:
    instance-id: ${spring.application.name}:${random.value}