logging:
  level:
    com:
      github:
        io:
          asyncer:
            r2dbc: DEBUG
server:
  port: '9560'
  forward-headers-strategy: framework
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://cokutan:123456@localhost:27017/blogapp
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.docker.internal:8080/auth/realms/blogapp
#Publish Application(Register with Eureka)
eureka:
  client:
    service-url:
      default-zone: http://${DISCOVERY_SERVICE_HOST:localhost}:8761/eureka
  # instance id for eureka server
  instance:
    instance-id: ${spring.application.name}:${random.value}
logging.level:
  root: DEBUG
  org.springframework.security: DEBUG