server:
  port: 9009

opensearch:
  host:
    name: ${ELASTIC_HOST:localhost}
    port: 9200
  password: admin
  username: admin
  http:
    scheme: https
spring:
  application:
    name: blogapp
  jpa:
    generate-ddl: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: create
    open-in-view: 'false'
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      data-locations: classpath:data.sql
      mode: always
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: '123456'
    username: cokutan
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/blogapp?createDatabaseIfNotExist=true
  profiles:
    active: production
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8888/auth/realms/blogapp

  #Publish Application(Register with Eureka)
  eureka:
    client:
      service-url:
        default-zone: http://localhost:8761/eureka
  # instance id for eureka server
    instance:
      instance-id: ${spring.application.name}:${random.value}