logging:
  level:
    com:
      github:
        io:
          asyncer:
            r2dbc: DEBUG
server:
  port: '9560'
  forward-headers-strategy: framework
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: blogapp-webflux
  r2dbc:
    password: '123456'
    ssl: 'false'
    url: r2dbc:pool:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3307}/blogapp?allowPublicKeyRetrieval=true
    username: cokutan
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:8888/auth/realms/blogapp
#Publish Application(Register with Eureka)
eureka:
  client:
    service-url:
      default-zone: http://${DISCOVERY_SERVICE_HOST:localhost}:8761/eureka
  # instance id for eureka server
  instance:
    instance-id: ${spring.application.name}:${random.value}
logging.level:
  root: DEBUG
  org.springframework.security: DEBUG