server:
  port: 9010
  forward-headers-strategy: framework
keycloak:
  auth-server-url: http://keycloak.docker.internal:8080/auth
  realm: blogapp
  client-id: blogapp
  client-secret: FsZL17sZd2cSp7bSnCrDdIcS6yuqefC6
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: blogapp-usermanagement
  data:
    mongodb:
      uri: mongodb://cokutan:123456@localhost:27017/blogapp


  #Publish Application(Register with Eureka)
  eureka:
    client:
      service-url:
        default-zone: http://${DISCOVERY_SERVICE_HOST:localhost}:8761/eureka
  # instance id for eureka server
    instance:
      instance-id: ${spring.application.name}:${random.value}

  logging.level:
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE