version: '3.8'
services:
  spring-app:
    build: .
    container_name: 'demo-blogapp'
    restart: 'always'
    ports:
      - '8080:8080'
    networks:
      - mysql-network
    depends_on:
      - db  
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/blogapp
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'blogapp'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'cokutan'
      # You can use whatever password you like
      MYSQL_PASSWORD: '123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_TCP_PORT: '3307'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3307'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - mysql-network
 # Names our volume
volumes:
 my-db:
networks:
 mysql-network: